repos:
  - repo: local
    hooks:
      # Hooks for workspace
      - id: cargo-fmt-workspace
        name: Cargo format for workspace
        language: "rust"
        entry: cargo +1.87.0 fmt --manifest-path ./Cargo.toml --all
        pass_filenames: false
        types_or: ["rust", "cargo", "cargo-lock"]
        files: .
      - id: cargo-clippy-workspace
        name: Cargo clippy for workspace
        language: "rust"
        entry: cargo +1.87.0 clippy --manifest-path ./Cargo.toml --tests -- -D warnings
        pass_filenames: false
        types_or: ["rust", "cargo", "cargo-lock"]
        files: .
      - id: cargo-test-workspace
        name: Cargo test for workspace
        language: "rust"
        entry: cargo +1.87.0 test --manifest-path ./Cargo.toml
        pass_filenames: false
        types_or: ["rust", "cargo", "cargo-lock"]
        files: .
