name: Pre-commit checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Need to grab the history of the PR
          fetch-depth: 0

      - name: Set up Python (for pre-commit)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.87.0
          components: clippy
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-12-03
          components: rustfmt

      - name: Run pre-commit on PR diff
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          pre-commit run --from-ref "${{ github.event.pull_request.base.sha }}" \
                         --to-ref "${{ github.event.pull_request.head.sha }}"

      - name: Run pre-commit on all files (non-PR pushes)
        if: ${{ github.event_name != 'pull_request' }}
        run: pre-commit run --all-files
